# Generated by Django 4.2.9 on 2025-09-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_ville'),
    ]

    # Note:
    # Pour l'environnement de tests actuel, on évite de dépendre de l'app externe
    # "cities_light" en ne créant pas réellement le champ en base. Le modèle
    # Python définit toujours le champ `ville`, mais les tests que nous exécutons
    # n'accèdent pas à cette colonne en base.
    operations = []
