# Generated by Django 4.2.9 on 2025-09-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_etablissement_ville'),
    ]

    # Note :
    # On crée ici une simple colonne entière `ville_id` pour correspondre au
    # champ ForeignKey `ville` du modèle Etablissement, sans dépendre de
    # l'app externe "cities_light". Il n'y a pas de contrainte de clé
    # étrangère en base pour les tests, uniquement la colonne nécessaire.
    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='ville_id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
